language: generic

sudo: required
services:
    - docker

script:
  # only build
    # - make build-testeall
  # build and then push to Docker Hub
    - docker build -t lujianmei/metabase-docker:latest .
    - docker login -u=$(DOCKER_NAME) -p=$(DOCKER_PASSWORD)
	  - docker push lujianmei/metabase-docker:latest
